dataset:
  train:
    audio_pathlist_path: "train_dataset/libritts-r_audio_pathlist.txt"
    pitch_label_pathlist_path: null
    length_file_path: "train_dataset/libritts-r_audio_length.txt"
    batch_bins: 21880
    root_dir: "train_dataset"
  valid:
    audio_pathlist_path: "train_dataset/mir1k_eval_250_audio_pathlist.txt"
    pitch_label_pathlist_path: "train_dataset/mir1k_eval_250_pitch_label_pathlist.txt"
    length_file_path: "train_dataset/mir1k_eval_250_audio_length.txt"
    batch_bins: 20199
    root_dir: "train_dataset"
  test_num: 128
  eval_times_num: 1
  seed: 42
  sample_rate: 24000

  # ピッチシフト
  pitch_shift_range: 14

network:
  sample_rate: 24000
  frame_length: 120

  # Pitch Encoder
  f0_bins: 1024
  bap_bins: 8
  nansy_conv_channels: 128 # NOTE: 論文で不明記
  nansy_num_resblocks: 2
  nansy_resblock_kernel_size: 3
  nansy_gru_hidden_size: 256 # NOTE: 論文で不明記
  nansy_gru_bidirectional: true # NOTE: 論文で不明記

  # CQT
  cqt_bins: 176
  cqt_total_bins: 205
  cqt_bins_per_octave: 24
  cqt_fmin: 32.70
  cqt_filter_scale: 0.5

  # Pitch Guide Generator
  pitch_guide_window_size: 50 # NOTE: 論文で不明記
  pitch_guide_shs_n_max: 10 # NOTE: 論文で不明記
  pitch_guide_f_min: 20.0
  pitch_guide_f_max: 2000.0
  pitch_guide_n_fft: 1024

  # Pseudo Spectrogram Generator
  pseudo_spec_epsilon: 0.001
  pseudo_spec_n_fft: 1024

  # V/UV Detector
  vuv_detector_eps: 1e-8
  vuv_threshold: 0.5

model:
  # 基本損失重み
  w_cons: 10.0
  w_guide: 1.0
  w_g_shift: 1.0
  w_pseudo: 10.0
  w_recon: 5.0

  # ノイズロバスト損失重み
  w_aug: 1.0
  w_g_aug: 1.0
  w_ap: 1.0

  # 損失パラメータ
  hinge_margin: 0.5
  ged_alpha: 0.1
  epsilon: 0.001
  huber_delta: 1.0

  # F0境界値
  f0_min: 20.0
  f0_max: 2000.0

  # BAP値域設定
  bap_min: -6.907755 # -60dB相当
  bap_max: 2.302585 # 20dB相当

  # ノイズロバスト化
  noise_snr_db_min: -6.0
  noise_snr_db_max: 20.0
  volume_change_db_range: 6.0

train:
  batch_size: 17
  eval_batch_size: 5
  min_batch_size: 1
  max_batch_size: 32

  log_epoch: 1
  eval_epoch: 1
  snapshot_epoch: 1
  stop_epoch: 5 # NOTE: 論文では10万ステップ
  model_save_num: 5
  optimizer:
    name: "adamw"
    lr: 0.0002
  scheduler: null
  prefetch_workers: 256
  preprocess_workers: 0
  use_gpu: true
  use_amp: true # NOTE: 論文では未使用かも

project:
  name: "init"
  category: "unofficial_slash"
